//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ActorMovie
    {
        public int ActorMovieId { get; set; }
        public int ActorId { get; set; }
        public int MovieId { get; set; }
    
        public virtual tbl_Actor tbl_Actor { get; set; }
        public virtual tbl_Movie tbl_Movie { get; set; }
    }
}
